---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload supervisord
  command: service supervisor restart

- name: restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted
